dependencies:
- anaconda-client
- autoflake
- black
- blackdoc
- bottleneck
- build
- conda-build
- dask
- flake8
- greyskull
- importlib_resources
- ipykernel
- ipython
- ipywidgets
- isort
- joblib
- matplotlib
- nbsphinx
- netcdf4
- numpy
- pip
- pre-commit
- pyls-black
- pyls-isort
- pyls-mypy
- pytest
- pytest-cov
- python=3.9
- recommonmark
- scikit-image
- scipy
- setuptools
- setuptools-scm
- setuptools_scm_git_archive
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-spelling
- tox-conda
- tqdm
- twine
- xarray
- pip:
  - pyenchant
name: lnpy-env
