dependencies:
- autoflake
- black
- blackdoc
- bottleneck
- dask
- flake8
- importlib_resources
- ipykernel
- ipython
- ipywidgets
- isort
- joblib
- matplotlib
- nbsphinx
- netcdf4
- numpy
- pip
- pre-commit
- pyls-black
- pyls-isort
- pyls-mypy
- pytest
- pytest-cov
- python=3.9
- scikit-image
- scipy
- setuptools-scm
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-spelling
- tox-conda
- tqdm
- xarray
- pip:
  - pyenchant
name: lnpy-env
