dependencies:
- bottleneck
- importlib_resources
- ipykernel
- ipython
- ipywidgets
- joblib
- matplotlib
- netcdf4
- numpy
- pytest
- pytest-cov
- pytest-xdist
- python>=3.8,<3.11
- scikit-image
- scipy
- setuptools-scm
- tqdm
- xarray
name: lnpy-env
