dependencies:
  - bottleneck
  - importlib_resources
  - ipykernel
  - ipython
  - ipywidgets
  - joblib
  - matplotlib
  - module-utilities >= 0.1
  - netcdf4
  - numpy
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python>=3.8,<=3.11
  - scikit-image
  - scipy
  - setuptools-scm
  - tqdm
  - xarray
  - pip:
      - pytest-accept
name: lnpy-env
