test:
  imports:
    - lnpy
    - lnPi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/tmmc-lnpy
  summary: Analysis of lnPi results from TMMC simulation
  description: |
    A package to analyze data from Transition Matrix Monte Carlo (tmmc)
    simulation. The main output from TMMC simulations, "lnPi", provides a
    means to calculate a host of thermodynamic properties. Moreover, if "lnPi"
    is calculated at a specific chemical potential, it can be reweighted to provide
    thermodynamic information at a different chemical potential.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
